include:
  - project: ci/cd
    file: version.yml

workflow: !reference [.ignore-bot-changes-rules]

stages:
- build
- deploy

build:
  stage: build
  image: node:16.20-alpine3.17
  script:
    - npm ci
    - npm run build-only
    - npm run dist
  artifacts:
    paths:
      - opcua-browser.zip

push-docker-image:
  extends: .docker-image
  stage: deploy

increase-version:
  extends: .increase-version
  stage: deploy
