include:
  - project:/ci/cd/version.yml


stages:
- build

build:
  stage: build
  image: node:16.20-alpine3.17
  script:
    - npm build
    - npm dist
  artifacts:
    paths:
      - opcua-client.zip
