include:
  - project: ci/cd
    file: version.yml


stages:
- build
- deploy

build:
  stage: build
  image: node:16.20-alpine3.17
  script:
    - npm install --production
    - npm run build
    - npm run dist
  artifacts:
    paths:
      - opcua-client.zip

push-docker-image:
  extends: .docker-image
  stage: deploy

increase-version:
  extends: .increase-version
  stage: deploy
